from __future__ import annotations

from typing import Any, Protocol


class _SubsystemBase(Protocol):
    def kind(self) -> str: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...


class Subsystem(_SubsystemBase, Protocol):
    def enqueue(self, sqe: Any) -> bool: ...
    def flush(self, time: int) -> None: ...


class SubsystemDST(_SubsystemBase, Protocol):
    def process(self, sqes: list[Any]) -> list[Any]: ...
