from __future__ import annotations

from typing import Protocol


class Subsystem(Protocol):
    def kind(self) -> str: ...
    def addr(self) -> str: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
